# Generated by Django 5.0 on 2023-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
